/* 
    Simple DirectMedia Layer
    Copyright (C) 1997-2025 Sam Lantinga <slouken@libsdl.org>
    Modified for YiaLite
*/

#ifndef C_YIALITE_SCANCODE_H
#define C_YIALITE_SCANCODE_H

typedef enum YiaLite_Scancode
{
    YIALITE_SCANCODE_UNKNOWN = 0,

    YIALITE_SCANCODE_A = 4,
    YIALITE_SCANCODE_B = 5,
    YIALITE_SCANCODE_C = 6,
    YIALITE_SCANCODE_D = 7,
    YIALITE_SCANCODE_E = 8,
    YIALITE_SCANCODE_F = 9,
    YIALITE_SCANCODE_G = 10,
    YIALITE_SCANCODE_H = 11,
    YIALITE_SCANCODE_I = 12,
    YIALITE_SCANCODE_J = 13,
    YIALITE_SCANCODE_K = 14,
    YIALITE_SCANCODE_L = 15,
    YIALITE_SCANCODE_M = 16,
    YIALITE_SCANCODE_N = 17,
    YIALITE_SCANCODE_O = 18,
    YIALITE_SCANCODE_P = 19,
    YIALITE_SCANCODE_Q = 20,
    YIALITE_SCANCODE_R = 21,
    YIALITE_SCANCODE_S = 22,
    YIALITE_SCANCODE_T = 23,
    YIALITE_SCANCODE_U = 24,
    YIALITE_SCANCODE_V = 25,
    YIALITE_SCANCODE_W = 26,
    YIALITE_SCANCODE_X = 27,
    YIALITE_SCANCODE_Y = 28,
    YIALITE_SCANCODE_Z = 29,

    YIALITE_SCANCODE_1 = 30,
    YIALITE_SCANCODE_2 = 31,
    YIALITE_SCANCODE_3 = 32,
    YIALITE_SCANCODE_4 = 33,
    YIALITE_SCANCODE_5 = 34,
    YIALITE_SCANCODE_6 = 35,
    YIALITE_SCANCODE_7 = 36,
    YIALITE_SCANCODE_8 = 37,
    YIALITE_SCANCODE_9 = 38,
    YIALITE_SCANCODE_0 = 39,

    YIALITE_SCANCODE_RETURN = 40,
    YIALITE_SCANCODE_ESCAPE = 41,
    YIALITE_SCANCODE_BACKSPACE = 42,
    YIALITE_SCANCODE_TAB = 43,
    YIALITE_SCANCODE_SPACE = 44,

    YIALITE_SCANCODE_MINUS = 45,
    YIALITE_SCANCODE_EQUALS = 46,
    YIALITE_SCANCODE_LEFTBRACKET = 47,
    YIALITE_SCANCODE_RIGHTBRACKET = 48,
    YIALITE_SCANCODE_BACKSLASH = 49, 
    YIALITE_SCANCODE_NONUSHASH = 50,
    YIALITE_SCANCODE_SEMICOLON = 51,
    YIALITE_SCANCODE_APOSTROPHE = 52,
    YIALITE_SCANCODE_GRAVE = 53, 
    YIALITE_SCANCODE_COMMA = 54,
    YIALITE_SCANCODE_PERIOD = 55,
    YIALITE_SCANCODE_SLASH = 56,

    YIALITE_SCANCODE_CAPSLOCK = 57,

    YIALITE_SCANCODE_F1 = 58,
    YIALITE_SCANCODE_F2 = 59,
    YIALITE_SCANCODE_F3 = 60,
    YIALITE_SCANCODE_F4 = 61,
    YIALITE_SCANCODE_F5 = 62,
    YIALITE_SCANCODE_F6 = 63,
    YIALITE_SCANCODE_F7 = 64,
    YIALITE_SCANCODE_F8 = 65,
    YIALITE_SCANCODE_F9 = 66,
    YIALITE_SCANCODE_F10 = 67,
    YIALITE_SCANCODE_F11 = 68,
    YIALITE_SCANCODE_F12 = 69,

    YIALITE_SCANCODE_PRINTSCREEN = 70,
    YIALITE_SCANCODE_SCROLLLOCK = 71,
    YIALITE_SCANCODE_PAUSE = 72,
    YIALITE_SCANCODE_INSERT = 73, 

    YIALITE_SCANCODE_HOME = 74,
    YIALITE_SCANCODE_PAGEUP = 75,
    YIALITE_SCANCODE_DELETE = 76,
    YIALITE_SCANCODE_END = 77,
    YIALITE_SCANCODE_PAGEDOWN = 78,
    YIALITE_SCANCODE_RIGHT = 79,
    YIALITE_SCANCODE_LEFT = 80,
    YIALITE_SCANCODE_DOWN = 81,
    YIALITE_SCANCODE_UP = 82
} YiaLite_Scancode;

#endif