/* 
    Simple DirectMedia Layer
        Copyright (C) 1997-2025 Sam Lantinga <slouken@libsdl.org>
*/

#ifndef C_YIALITE_MOUSE_BUTTON_H
#define C_YIALITE_MOUSE_BUTTON_H

#include <stdint.h>

typedef uint8_t YiaLite_MouseButton;

#define C_YIALITE_MOUSE_BUTTON_LEFT     1
#define C_YIALITE_MOUSE_BUTTON_MIDDLE   2
#define C_YIALITE_MOUSE_BUTTON_RIGHT    3
#define C_YIALITE_MOUSE_BUTTON_X1       4
#define C_YIALITE_MOUSE_BUTTON_X2       5

#define C_YIALITE_MOUSE_BUTTON_MASK(X)  (1u << ((X)-1))

typedef enum YiaLite_MouseButtonFlags
{
    YIALITE_MOUSE_BUTTON_LMASK = C_YIALITE_MOUSE_BUTTON_MASK(C_YIALITE_MOUSE_BUTTON_LEFT),
    YIALITE_MOUSE_BUTTON_MMASK = C_YIALITE_MOUSE_BUTTON_MASK(C_YIALITE_MOUSE_BUTTON_MIDDLE),
    YIALITE_MOUSE_BUTTON_RMASK = C_YIALITE_MOUSE_BUTTON_MASK(C_YIALITE_MOUSE_BUTTON_RIGHT),
    YIALITE_MOUSE_BUTTON_X1MASK = C_YIALITE_MOUSE_BUTTON_MASK(C_YIALITE_MOUSE_BUTTON_X1),
    YIALITE_MOUSE_BUTTON_X2MASK = C_YIALITE_MOUSE_BUTTON_MASK(C_YIALITE_MOUSE_BUTTON_X2),
} YiaLite_MouseButtonFlags;

#endif