#ifndef MOUSE_BUTTON_H
#define MOUSE_BUTTON_H

#define MOUSE_BUTTON_LEFT     1
#define MOUSE_BUTTON_MIDDLE   2
#define MOUSE_BUTTON_RIGHT    3
#define MOUSE_BUTTON_X1       4
#define MOUSE_BUTTON_X2       5

#define MOUSE_BUTTON_MASK(X)  (1u << ((X)-1))
#define MOUSE_BUTTON_LMASK    MOUSE_BUTTON_MASK(MOUSE_BUTTON_LEFT)
#define MOUSE_BUTTON_MMASK    MOUSE_BUTTON_MASK(MOUSE_BUTTON_MIDDLE)
#define MOUSE_BUTTON_RMASK    MOUSE_BUTTON_MASK(MOUSE_BUTTON_RIGHT)
#define MOUSE_BUTTON_X1MASK   MOUSE_BUTTON_MASK(MOUSE_BUTTON_X1)
#define MOUSE_BUTTON_X2MASK   MOUSE_BUTTON_MASK(MOUSE_BUTTON_X2)

#endif