function(yia_collect_link_dependencies targets_var libs_var packages_var)
  set(_pending ${ARGN})
  set(_visited "")
  set(_targets "")
  set(_plain "")
  set(_packages "")

  while(_pending)
    list(POP_FRONT _pending _item)
    if(_item IN_LIST _visited)
      continue()
    endif()
    list(APPEND _visited "${_item}")

    if(TARGET "${_item}")
      get_target_property(_imported "${_item}" IMPORTED)
      get_target_property(_type "${_item}" TYPE)
      if(NOT _imported AND
         (_type STREQUAL "STATIC_LIBRARY" OR
          _type STREQUAL "SHARED_LIBRARY" OR
          _type STREQUAL "MODULE_LIBRARY"))
        get_target_property(_real "${_item}" ALIASED_TARGET)
        if(_real)
          list(APPEND _targets "${_real}")
        else()
          list(APPEND _targets "${_item}")
        endif()
      endif()
      get_target_property(_interface "${_item}" INTERFACE_LINK_LIBRARIES)
      if(_interface)
        list(APPEND _pending ${_interface})
      endif()
    elseif(_item MATCHES "^\\$<LINK_ONLY:(.*)>$")
      list(APPEND _pending "${CMAKE_MATCH_1}")
    elseif(_item MATCHES "^([A-Za-z0-9_]+)::")
      # An imported target defined in a subdirectory, so invisible here.
      list(APPEND _plain "${_item}")
      list(APPEND _packages "${CMAKE_MATCH_1}")
    elseif(NOT _item MATCHES "^\\$<")
      list(APPEND _plain "${_item}")
    endif()
  endwhile()

  list(REMOVE_DUPLICATES _targets)
  list(REMOVE_DUPLICATES _plain)
  list(REMOVE_DUPLICATES _packages)
  set(${targets_var} "${_targets}" PARENT_SCOPE)
  set(${libs_var} "${_plain}" PARENT_SCOPE)
  set(${packages_var} "${_packages}" PARENT_SCOPE)
endfunction()
